### ISSUE TITLE
服务管理界面显示分片数量

### ISSUE THREAD

**Issue by qichang1984** [upmio/upm#13]
对于分片架构，在部署架构里面，新增分片信息，比如：主备(3分片)
但是对于没有分片的不需要显示。分片结构最少2个分片。
![image](https://user-images.githubusercontent.com/8721013/34551855-5f84c6d6-f158-11e7-8cdc-673c3d4a2bbe.png)

**Comment by linleybao** [comment]
这个需求针对UPSQL
